# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codigoe', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigop', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('numerot', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('fechaapertura', models.DateField(auto_now_add=True)),
                ('ciudad', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
                ('codigoe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Estado')),
                ('codigop', models.ManyToManyField(to='inventario.Producto')),
            ],
        ),
    ]
